### ISSUE TITLE
What's the structure of the data?

### ISSUE THREAD

**Issue by noparkee** [alexmonti19/dagnet#18]
Hello! Thank you for your poject!

I downloaded npy data from 
When I opened the npy data, it's shape was (14032, 50, 11, 4).
Can I know what each number means? According to your paper, I think that 14032 is the number of sequences and 50 is the length of each sequence, but I don't know what 11 and 4 means.

Thank you!

**Comment by alexmonti19** [comment]
Hi,
thanks for your interest in our research!

Take a look at [datasets/README.md](./datasets/README.md): as you said, the first dimension is the number of sequences and the second is number of timesteps; the formers are the players (5 attackers + 5 defenders + ball) and their position in the court. The 4th channel in the last dimension can always be dropped (if I recall correctly, when I downloaded the data for the first time they said it was a boolean flag for the player with ball possession, but I didn't found it correct), and since we're looking at players positions from a top-down view, we can also discard the z-channel keeping only xy.

Alex

**Comment by noparkee** [comment]
Thank you so much for your kind answer😀!

**Comment by noparkee** [comment]
Hello, I have one more question.

According to your paper, the NBA dataset is from “[SportVU - STATS Perform](https://www.statsperform.com/team-performance/basketball/optical-tracking)”.
But I couldn't find more details there. May I know if it is the same as the data on this [github link](https://github.com/linouk23/NBA-Player-Movements)?

Thank you.

**Comment by alexmonti19** [comment]
Hi,
yes unfortunately SportVU turned the dataset private a few years ago for commercial purposes, hence we can only rely on mirrors or GitHub repos. Personally, I found the dataset [here](https://github.com/chychen/BasketballGAN); I can't ensure the data from your link are exactly the same, but these versions as many others here on Github are all rip-offs of the original dataset, so they are surely coherent.

Alex

**Comment by noparkee** [comment]
Thank you again for your answer!
