### ISSUE TITLE
First-person perspective?

### ISSUE THREAD

**Issue by 1187697147** [alexmonti19/dagnet#2]
Hi,
I have just learned something about Motion Trajectory Prediction, i feel confused that can this work support first-person perspective? I find lots of papers show their results just from  god perspective, can these papers work well when i use them from first-person perspective?

**Comment by alexmonti19** [comment]
Hi!

All the architectures in this field work from a top-down view of the scene mainly because it allows using a global/absolute reference system for the entire scene, making it easier for the network to extract useful motion features and patterns. 

I think working for a first-person perspective is possible, but I have some doubts about the precision of the final results since this choice would require some tricky pre and post-processing steps involving perspective and geometry (and, for DAG-Net you also need to think of a way of mapping our 2D goals into some type of 3D clues). 

As it is, DAG-Net doesn't support the first-person perspective, but feel free to fork the repo and start from our code :)

Alex
