### ISSUE TITLE
expname issue

### ISSUE THREAD

**Issue by NehaPusalkar** [alexmonti19/dagnet#3]
How is the --run parameter used? I wish to execute evaluate_sdd.py but /runs/dagnet is empty. 
I tried with exp_sdd_best from pretrained models still gettibg this error 
FileNotFoundError: [Errno 2] No such file or directory: '/home/runs/dagnet/exp_sdd_best'

**Comment by alexmonti19** [comment]
Hi and thanks for your interest in our research!

The `--run`  parameter specifies the experiment/run name used when instantiating a new training with one the different `train_***.py` scripts. If you execute the evaluation script without having trained anything, the checkpoint loading will since the runs folder is empty.

One option, as we pointed out in the _pretrained_models/README.md_ is to used one of our pretrained checkpoints: as the readme says, you have to copy relative exp folder in the `runs\<model>` folder (in your case, for evaluating _dagnet_ on _SDD_, you should copy: `pretrained_models/_dagnet_/_exp_sdd_best_` inside `runs\_dagnet_` ; be sure to exactly copy the `exp_sdd_best/` folder, it already includes all the necessary organized subfolders and files).

**Comment by alexmonti19** [comment]
PS: by running a quick local evaluation with the pretrained checkpoint everything seems fine, I only found a little bug on line 17
https://github.com/alexmonti19/dagnet/blob/a4c4e2a21f654a368b6f66c0b809baf7102e5a73/models/dagnet/evaluate_sdd.py#L170

It should be _logging_ and not _loggin_. I have quickly committed a little bugifx, make sure to pull the changes 👍

**Comment by NehaPusalkar** [comment]
Hi. Thank you for the quick reply. Even after moving the exp_sdd_best to runs/dagnet I am facing some issues:
1) When I run the training script from models/dagnet/ I face this issue
  File "train_sdd.py", line 13, in <module>
    from models.dagnet.model import DAGNet
ModuleNotFoundError: No module named 'models'
Do you have any suggestions on how to run this or how to set the PYTHONPATH
2)Also when I run evaluate_sdd.py it says this file is missing
runs/dagnet/exp_sdd_best/exp_sdd_best_eval.log'  Do I need to train the model again in order to generate this file?

Thanks in advance!

**Comment by alexmonti19** [comment]
> Hi. Thank you for the quick reply. Even after moving the exp_sdd_best to runs/dagnet I am facing some issues:
> 
> 1. When I run the training script from models/dagnet/ I face this issue
>    File "train_sdd.py", line 13, in 
>    from models.dagnet.model import DAGNet
>    ModuleNotFoundError: No module named 'models'
>    Do you have any suggestions on how to run this or how to set the PYTHONPATH

If you are on Linux/UNIX

```
export PYTHONPATH="${PYTHONPATH}:<absolute_path_to_project_root_directory>"
```

should do.


>    2)Also when I run evaluate_sdd.py it says this file is missing
>    runs/dagnet/exp_sdd_best/exp_sdd_best_eval.log'  Do I need to train the model again in order to generate this file?

Could you give me the error full stacktrace? It's odd because `<run_name>_eval.log` is the log file where we print the evaluation results and is created by the script itself here 
https://github.com/alexmonti19/dagnet/blob/29a00bf8537c345d9c9d3fa3ff195915dd7d2c39/models/dagnet/evaluate_sdd.py#L141-L142
so it should not be giving you any error.

**Comment by NehaPusalkar** [comment]
Thank you for your help. The evaluation issue is now resolved.

**Comment by Kevin-228322** [comment]
Excuse me, I also meet the same question .
When I run the training script from models/dagnet/ I face this issue
File "train_sdd.py", line 13, in
from models.dagnet.model import DAGNet
ModuleNotFoundError: No module named 'models'
How can I solve the problem?
thanks you

**Comment by alexmonti19** [comment]
> Excuse me, I also meet the same question .
> When I run the training script from models/dagnet/ I face this issue
> File "train_sdd.py", line 13, in
> from models.dagnet.model import DAGNet
> ModuleNotFoundError: No module named 'models'
> How can I solve the problem?
> thanks you

Hi!
The solution is a few replies above. You to point your PYTHONPATH to the project root directory. If you're on Linux/UNIX

```
export PYTHONPATH="${PYTHONPATH}:<absolute_path_to_project_root_directory>"
```

should do.

**Comment by Kevin-228322** [comment]
> > Excuse me, I also meet the same question .
> > When I run the training script from models/dagnet/ I face this issue
> > File "train_sdd.py", line 13, in
> > from models.dagnet.model import DAGNet
> > ModuleNotFoundError: No module named 'models'
> > How can I solve the problem?
> > thanks you
> 
> Hi!
> The solution is a few replies above. You have to point your PYTHONPATH to the project root directory. If you're on Linux/UNIX
> 
> ```
> export PYTHONPATH="${PYTHONPATH}:<absolute_path_to_project_root_directory>"
> ```
> 
> should do.

thanks
